# Generated by Django 3.2 on 2021-12-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0005_alter_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='quality'),
        ),
    ]
