# Generated by Django 3.2 on 2021-12-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0007_alter_item_item_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='image'),
        ),
    ]
