# Generated by Django 3.2 on 2021-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0008_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='image'),
        ),
    ]
